/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.swing;

import controlador.Controlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import vista.interfaz.VistaPrincipal;

/**
 *
 * @author franc
 */
public class VistaPrincipalSwing extends javax.swing.JFrame implements VistaPrincipal {

    /**
     * Creates new form VistaPrincipalSwing
     */
    public VistaPrincipalSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoProducto = new javax.swing.JButton();
        btnNuevoPedido = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevoProducto.setText("Nuevo Producto");
        btnNuevoProducto.setName("btnNuevoProducto"); // NOI18N

        btnNuevoPedido.setText("Nuevo Pedido");
        btnNuevoPedido.setName("btnNuevoPedido"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnNuevoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(btnNuevoPedido)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoProducto)
                    .addComponent(btnNuevoPedido))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoPedido;
    private javax.swing.JButton btnNuevoProducto;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(Controlador controlador) {
        this.btnNuevoPedido.addActionListener(controlador);
        this.btnNuevoPedido.setActionCommand(VistaPrincipal.NUEVO_PEDIDO);
        
        this.btnNuevoProducto.addActionListener(controlador);
        this.btnNuevoProducto.setActionCommand(VistaPrincipal.NUEVO_PRODUCTO);
    }

    @Override
    public void iniciarVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }
}
